spring.application.name=FoodOrderingSystem


# configure the database with UserID and password
#url
spring.datasource.url= jdbc:mysql://localhost:3306/foododering
#username
spring.datasource.username=root
#password
spring.datasource.password=Root1710

#Hibernate -> Create new, Update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
