# Make sure your database exists in MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Username (default is root)
spring.datasource.username=root

# Replace this with your actual MySQL Workbench/local server password
spring.datasource.password=Monika@302004

spring.jpa.hibernate.ddl-auto=update